language: python

python:
    - "2.6"
    - "2.7"

env:
    global:
        - BEANSTALKD=./beanstalkd

install:
    # Install most recent beanstalkd from source
    - wget https://github.com/kr/beanstalkd/archive/v1.10.tar.gz
    - tar xf v1.10.tar.gz
    - make -C beanstalkd-1.10/
    - mv beanstalkd-1.10/beanstalkd .
    # Install Python dependencies.
    - pip install -r .travis-requirements.txt --use-mirrors

script: nosetests -c .nose.cfg

branches:
    only:
        - master
        - wip-travisci
